# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "linux" do |linux|
        linux.vm.box = "fgrehm/trusty64-lxc"
        #linux.vm.box_url ="https://dl.dropboxusercontent.com/u/67225617/lxc-vagrant/lxc-squeeze64-puppet3-2013-07-27.box"
        #linux.vm.network "private_network", ip: "192.168.33.10"
        linux.vm.synced_folder "../app", "/app"
    end

    config.vm.provision :shell, :path => "puppet_prep.sh"

    config.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "puppet/manifests"
        puppet.module_path = "puppet/modules"
        puppet.manifest_file  = "site.pp"
    end
end
